export const themes = {
    default: {
        author: "Doras.to",
        card: "border-green-500/30 bg-black/80 backdrop-blur-md",
        avatarBorder: "relative rounded",
        avatarFallback: "bg-green-500",
        badge: "bg-green-500",
        text: "text-green-500",
        timestampText: "text-muted-foreground",
    },
    pink: {
        author: "Doras.to",
        card: "bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600",
        avatarBorder: "relative rounded",
        avatarFallback: "bg-pink-900",
        badge: "bg-pink-300",
        text: "text-white",
        timestampText: "text-gray-300",
    },
    "neon-pink": {
        author: "Doras.to",
        card: "bg-black shadow-[0_0_15px_rgba(236,72,153,0.5)] bg-gradient-to-r from-pink-500 via-fuchsia-500 to-pink-500",
        avatarBorder: "relative border-2 border-pink-300 ",
        avatarFallback: "bg-pink-900",
        badge: "bg-pink-300",
        text: "text-pink-300",
        timestampText: "text-pink-200",
    },
    "neon-blue": {
        author: "Doras.to",
        card: "bg-black shadow-[0_0_15px_rgba(59,130,246,0.5)] bg-gradient-to-r from-blue-500 via-cyan-500 to-blue-500",
        avatarBorder: "relative border-2 border-blue-300",
        avatarFallback: "bg-blue-900",
        badge: "bg-blue-300",
        text: "text-blue-300",
        timestampText: "text-blue-200",
    },
    "neon-purple": {
        author: "Doras.to",
        card: "bg-black shadow-[0_0_15px_rgba(147,51,234,0.5)] bg-gradient-to-r from-purple-500 via-violet-500 to-purple-500",
        avatarBorder: "relative border-2 border-purple-300",
        avatarFallback: "bg-purple-900",
        badge: "bg-purple-300",
        text: "text-purple-300",
        timestampText: "text-purple-200",
    },
    "neon-green": {
        author: "Doras.to",
        card: "bg-black shadow-[0_0_15px_rgba(34,197,94,0.5)] bg-gradient-to-r from-green-500 via-emerald-500 to-green-500",
        avatarBorder: "relative border-2 border-green-300",
        avatarFallback: "bg-green-900",
        badge: "bg-green-300",
        text: "text-green-300",
        timestampText: "text-green-200",
    },
    "sunset-orange": {
        author: "AI",
        card: "bg-gradient-to-r from-orange-400 via-orange-500 to-red-600",
        avatarBorder: "border-2 border-yellow-300 rounded",
        avatarFallback: "bg-red-800",
        badge: "bg-orange-300",
        text: "text-white",
        timestampText: "text-yellow-100",
    },
    "ocean-blue": {
        author: "AI",
        card: "bg-gradient-to-r from-blue-400 via-blue-500 to-blue-600",
        avatarBorder: "border-2 border-blue-200 rounded",
        avatarFallback: "bg-blue-700",
        badge: "bg-blue-300",
        text: "text-white",
        timestampText: "text-blue-100",
    },
    "pastel-purple": {
        author: "AI",
        card: "bg-gradient-to-r from-purple-200 via-purple-300 to-purple-400",
        avatarBorder: "border-2 border-purple-100 rounded",
        avatarFallback: "bg-purple-300",
        badge: "bg-purple-200",
        text: "text-gray-900",
        timestampText: "text-purple-500",
    },
    "dark-matte": {
        author: "AI",
        card: "bg-gray-800 shadow-lg border border-gray-700",
        avatarBorder: "border-2 border-gray-600 rounded",
        avatarFallback: "bg-gray-700",
        badge: "bg-gray-500",
        text: "text-white",
        timestampText: "text-gray-400",
    },
    "lime-light": {
        author: "AI",
        card: "bg-gradient-to-r from-lime-300 via-lime-400 to-lime-500",
        avatarBorder: "border-2 border-lime-200 rounded",
        avatarFallback: "bg-lime-700",
        badge: "bg-lime-300",
        text: "text-black",
        timestampText: "text-lime-100",
    },
    "cotton-candy": {
        author: "AI",
        card: "bg-gradient-to-r from-pink-100 via-teal-200 to-lime-300",
        avatarBorder: "border-2 border-pink-300 rounded",
        avatarFallback: "bg-pink-200",
        badge: "bg-pink-300",
        text: "text-gray-900",
        timestampText: "text-teal-500",
    },
    "electric-yellow": {
        author: "AI",
        card: "bg-gradient-to-r from-yellow-500 via-yellow-600 to-yellow-700",
        avatarBorder: "border-2 border-yellow-300 rounded",
        avatarFallback: "bg-yellow-800",
        badge: "bg-yellow-400",
        text: "text-black",
        timestampText: "text-yellow-200",
    },
    "dark-mint": {
        author: "AI",
        card: "bg-gradient-to-r from-teal-700 via-teal-800 to-teal-900",
        avatarBorder: "border-2 border-teal-500 rounded",
        avatarFallback: "bg-teal-900",
        badge: "bg-teal-300",
        text: "text-white",
        timestampText: "text-teal-200",
    },
    "cyberpunk-neon": {
        author: "AI",
        card: "bg-black shadow-[0_0_20px_rgba(0,255,255,0.8)]",
        avatarBorder: "border-2 border-cyan-400 rounded",
        avatarFallback: "bg-cyan-800",
        badge: "bg-cyan-300",
        text: "text-cyan-300",
        timestampText: "text-cyan-200",
    },
    "retro-sunset": {
        author: "AI",
        card: "bg-gradient-to-r from-pink-500 via-orange-400 to-yellow-500",
        avatarBorder: "border-2 border-yellow-500 rounded",
        avatarFallback: "bg-orange-800",
        badge: "bg-orange-300",
        text: "text-yellow-200",
        timestampText: "text-pink-200",
    },
    "galaxy-dreams": {
        author: "AI",
        card: "bg-gradient-to-r from-purple-600 via-blue-800 to-indigo-900",
        avatarBorder: "border-2 border-indigo-300 rounded",
        avatarFallback: "bg-indigo-800",
        badge: "bg-indigo-500",
        text: "text-white",
        timestampText: "text-purple-300",
    },
    "forest-vibes": {
        author: "AI",
        card: "bg-gradient-to-r from-green-500 via-green-600 to-green-700",
        avatarBorder: "border-2 border-green-300 rounded",
        avatarFallback: "bg-green-800",
        badge: "bg-green-400",
        text: "text-green-200",
        timestampText: "text-green-100",
    },
    "midnight-black": {
        author: "AI",
        card: "bg-black shadow-xl border border-gray-600",
        avatarBorder: "border-2 border-gray-500 rounded",
        avatarFallback: "bg-gray-800",
        badge: "bg-gray-400",
        text: "text-white",
        timestampText: "text-gray-300",
    },
    "pink-lemonade": {
        author: "AI",
        card: "bg-gradient-to-r from-pink-300 via-yellow-400 to-pink-500",
        avatarBorder: "border-2 border-pink-300 rounded",
        avatarFallback: "bg-pink-500",
        badge: "bg-yellow-300",
        text: "text-pink-600",
        timestampText: "text-yellow-200",
    },
    "tropical-oasis": {
        author: "AI",
        card: "bg-gradient-to-r from-teal-400 via-lime-500 to-yellow-500",
        avatarBorder: "border-2 border-lime-300 rounded",
        avatarFallback: "bg-lime-600",
        badge: "bg-teal-300",
        text: "text-white",
        timestampText: "text-lime-200",
    },
    "electric-blue": {
        author: "AI",
        card: "bg-gradient-to-r from-blue-600 via-blue-700 to-blue-800",
        avatarBorder: "border-2 border-blue-500 rounded",
        avatarFallback: "bg-blue-700",
        badge: "bg-blue-400",
        text: "text-white",
        timestampText: "text-blue-200",
    },
    "violet-mist": {
        author: "AI",
        card: "bg-gradient-to-r from-violet-300 via-violet-400 to-violet-500",
        avatarBorder: "border-2 border-violet-400 rounded",
        avatarFallback: "bg-violet-600",
        badge: "bg-violet-200",
        text: "text-violet-800",
        timestampText: "text-violet-200",
    },
    "burnt-amber": {
        author: "AI",
        card: "bg-gradient-to-r from-amber-500 via-amber-600 to-amber-700",
        avatarBorder: "border-2 border-amber-400 rounded",
        avatarFallback: "bg-amber-700",
        badge: "bg-amber-300",
        text: "text-white",
        timestampText: "text-amber-200",
    },
    "cosmic-void": {
        author: "AI",
        card: "bg-gradient-to-r from-indigo-900 via-purple-800 to-blue-900 shadow-[0_0_20px_rgba(138,43,226,0.6)]",
        avatarBorder: "border-2 border-indigo-500 rounded",
        avatarFallback: "bg-indigo-700",
        badge: "bg-purple-500",
        text: "text-indigo-300",
        timestampText: "text-purple-200",
    },
    "holographic-neon": {
        author: "AI",
        card: "bg-gradient-to-r from-cyan-300 via-purple-400 to-pink-500 shadow-[0_0_15px_rgba(0,255,255,0.7)]",
        avatarBorder: "border-2 border-cyan-500 rounded",
        avatarFallback: "bg-cyan-700",
        badge: "bg-cyan-400",
        text: "text-white",
        timestampText: "text-cyan-200",
    },
    "starlight-glow": {
        author: "AI",
        card: "bg-gradient-to-br from-white via-indigo-300 to-blue-500 shadow-[0_0_15px_rgba(255,255,255,0.8)]",
        avatarBorder: "border-2 border-indigo-400 rounded",
        avatarFallback: "bg-indigo-200",
        badge: "bg-blue-300",
        text: "text-white",
        timestampText: "text-indigo-200",
    },
    "nebula-radiance": {
        author: "AI",
        card: "bg-gradient-to-r from-fuchsia-600 via-purple-700 to-indigo-800 shadow-[0_0_25px_rgba(147,112,219,0.7)]",
        avatarBorder: "border-2 border-fuchsia-500 rounded",
        avatarFallback: "bg-fuchsia-700",
        badge: "bg-fuchsia-300",
        text: "text-white",
        timestampText: "text-fuchsia-200",
    },
    "quantum-flux": {
        author: "AI",
        card: "bg-gradient-to-r from-teal-500 via-green-600 to-blue-700 shadow-[0_0_20px_rgba(0,255,0,0.5)]",
        avatarBorder: "border-2 border-teal-400 rounded",
        avatarFallback: "bg-teal-700",
        badge: "bg-green-400",
        text: "text-teal-100",
        timestampText: "text-green-200",
    },
    "celestial-canopy": {
        author: "AI",
        card: "bg-gradient-to-r from-indigo-900 via-blue-800 to-gray-700 shadow-[0_0_20px_rgba(138,43,226,0.7)]",
        avatarBorder: "border-2 border-indigo-500 rounded",
        avatarFallback: "bg-indigo-700",
        badge: "bg-blue-400",
        text: "text-indigo-300",
        timestampText: "text-blue-200",
    },
    "pixel-pulse": {
        author: "AI",
        card: "bg-gradient-to-r from-pink-500 via-orange-500 to-yellow-500 shadow-[0_0_15px_rgba(255,165,0,0.6)]",
        avatarBorder: "border-2 border-orange-400 rounded",
        avatarFallback: "bg-orange-800",
        badge: "bg-yellow-400",
        text: "text-white",
        timestampText: "text-orange-200",
    },
    "shadow-nexus": {
        author: "AI",
        card: "bg-gradient-to-r from-black via-gray-900 to-purple-800 shadow-[0_0_25px_rgba(147,112,219,0.7)]",
        avatarBorder: "border-2 border-gray-700 rounded",
        avatarFallback: "bg-gray-800",
        badge: "bg-purple-500",
        text: "text-gray-300",
        timestampText: "text-purple-200",
    },
    "sunset-horizon": {
        author: "AI",
        card: "bg-gradient-to-r from-orange-600 via-red-500 to-pink-500 shadow-[0_0_20px_rgba(255,69,0,0.6)]",
        avatarBorder: "border-2 border-orange-400 rounded",
        avatarFallback: "bg-red-900",
        badge: "bg-yellow-400",
        text: "text-orange-200",
        timestampText: "text-yellow-300",
    },
    "crimson-abyss": {
        author: "AI",
        card: "bg-gradient-to-r from-red-900 via-maroon-800 to-black shadow-[0_0_25px_rgba(220,20,60,0.7)]",
        avatarBorder: "border-2 border-red-700 rounded",
        avatarFallback: "bg-maroon-900",
        badge: "bg-red-500",
        text: "text-red-300",
        timestampText: "text-red-200",
    },
    "frozen-glow": {
        author: "AI",
        card: "bg-gradient-to-r from-blue-700 via-cyan-500 to-white shadow-[0_0_20px_rgba(173,216,230,0.6)]",
        avatarBorder: "border-2 border-cyan-300 rounded",
        avatarFallback: "bg-blue-900",
        badge: "bg-cyan-400",
        text: "text-white",
        timestampText: "text-blue-200",
    },
    "infernal-core": {
        author: "AI",
        card: "bg-gradient-to-r from-black via-red-800 to-orange-600 shadow-[0_0_30px_rgba(255,69,0,0.8)]",
        avatarBorder: "border-2 border-red-600 rounded",
        avatarFallback: "bg-black",
        badge: "bg-red-400",
        text: "text-orange-200",
        timestampText: "text-orange-300",
    },
    "emerald-sanctuary": {
        author: "AI",
        card: "bg-gradient-to-r from-teal-800 via-green-700 to-lime-600 shadow-[0_0_20px_rgba(50,205,50,0.6)]",
        avatarBorder: "border-2 border-lime-400 rounded",
        avatarFallback: "bg-teal-900",
        badge: "bg-green-400",
        text: "text-lime-200",
        timestampText: "text-green-300",
    },
    "neon-stream": {
        author: "AI",
        card: "bg-gradient-to-r from-purple-700 via-indigo-600 to-blue-500 shadow-[0_0_15px_rgba(138,43,226,0.7)]",
        avatarBorder: "border-2 border-indigo-400 rounded",
        avatarFallback: "bg-purple-900",
        badge: "bg-indigo-500",
        text: "text-white",
        timestampText: "text-indigo-200",
    },
    "cyber-glitch": {
        author: "AI",
        card: "bg-gradient-to-r from-cyan-500 via-purple-600 to-pink-500 shadow-[0_0_20px_rgba(0,255,255,0.6)]",
        avatarBorder: "border-2 border-cyan-400 rounded",
        avatarFallback: "bg-purple-900",
        badge: "bg-pink-500",
        text: "text-white",
        timestampText: "text-cyan-200",
    },
    "dark-mode-pro": {
        author: "AI",
        card: "bg-gradient-to-r from-black via-gray-900 to-gray-700 shadow-[0_0_15px_rgba(128,128,128,0.5)]",
        avatarBorder: "border-2 border-gray-600 rounded",
        avatarFallback: "bg-gray-800",
        badge: "bg-gray-500",
        text: "text-gray-300",
        timestampText: "text-gray-400",
    },
    "hyper-flare": {
        author: "AI",
        card: "bg-gradient-to-r from-orange-600 via-red-600 to-purple-600 shadow-[0_0_30px_rgba(255,69,0,0.8)]",
        avatarBorder: "border-2 border-orange-500 rounded",
        avatarFallback: "bg-red-900",
        badge: "bg-purple-500",
        text: "text-orange-200",
        timestampText: "text-orange-300",
    },
    "gamer-energy": {
        author: "AI",
        card: "bg-gradient-to-r from-green-700 via-lime-600 to-yellow-500 shadow-[0_0_25px_rgba(50,205,50,0.7)]",
        avatarBorder: "border-2 border-lime-400 rounded",
        avatarFallback: "bg-green-900",
        badge: "bg-yellow-500",
        text: "text-lime-200",
        timestampText: "text-green-300",
    },
    "night-drive": {
        author: "AI",
        card: "bg-gradient-to-r from-blue-900 via-indigo-800 to-black shadow-[0_0_30px_rgba(0,0,255,0.7)]",
        avatarBorder: "border-2 border-indigo-500 rounded",
        avatarFallback: "bg-black",
        badge: "bg-blue-600",
        text: "text-indigo-200",
        timestampText: "text-blue-300",
    },
    "minimal-dark": {
        author: "AI",
        card: "bg-gray-900 shadow-lg",
        avatarBorder: "border border-gray-700 rounded",
        avatarFallback: "bg-gray-800",
        badge: "bg-gray-700",
        text: "text-gray-300",
        timestampText: "text-gray-500",
    },
    "classic-light": {
        author: "AI",
        card: "bg-white shadow-md",
        avatarBorder: "border border-gray-300 rounded",
        avatarFallback: "bg-gray-200",
        badge: "bg-gray-400",
        text: "text-gray-800",
        timestampText: "text-gray-500",
    },
    woodland: {
        author: "AI",
        card: "bg-green-900 shadow-md",
        avatarBorder: "border border-green-700 rounded",
        avatarFallback: "bg-green-800",
        badge: "bg-green-600",
        text: "text-green-300",
        timestampText: "text-green-400",
    },
    sandstorm: {
        author: "AI",
        card: "bg-yellow-200 shadow-md",
        avatarBorder: "border border-yellow-500 rounded",
        avatarFallback: "bg-yellow-300",
        badge: "bg-yellow-600",
        text: "text-yellow-900",
        timestampText: "text-yellow-700",
    },
    stealth: {
        author: "AI",
        card: "bg-black shadow-lg",
        avatarBorder: "border border-gray-800 rounded",
        avatarFallback: "bg-gray-900",
        badge: "bg-gray-700",
        text: "text-gray-400",
        timestampText: "text-gray-500",
    },
    "desert-stone": {
        author: "AI",
        card: "bg-orange-100 shadow-md",
        avatarBorder: "border border-orange-400 rounded",
        avatarFallback: "bg-orange-300",
        badge: "bg-orange-500",
        text: "text-orange-900",
        timestampText: "text-orange-700",
    },
    "royal-elegance": {
        author: "AI",
        card: "bg-purple-900 shadow-md",
        avatarBorder: "border border-purple-700 rounded",
        avatarFallback: "bg-purple-800",
        badge: "bg-purple-600",
        text: "text-purple-300",
        timestampText: "text-purple-400",
    },
    industrial: {
        author: "AI",
        card: "bg-gray-700 shadow-md",
        avatarBorder: "border border-gray-500 rounded",
        avatarFallback: "bg-gray-600",
        badge: "bg-gray-500",
        text: "text-gray-200",
        timestampText: "text-gray-400",
    },
    "forest-breeze": {
        author: "AI",
        card: "bg-gradient-to-r from-green-600 via-green-700 to-green-800 shadow-md",
        avatarBorder: "border-2 border-green-500 rounded",
        avatarFallback: "bg-green-400",
        badge: "bg-green-300",
        text: "text-white",
        timestampText: "text-green-100",
    },
    "mountain-dawn": {
        author: "AI",
        card: "bg-gradient-to-r from-blue-500 via-sky-400 to-blue-600 shadow-lg",
        avatarBorder: "border-2 border-blue-400 rounded",
        avatarFallback: "bg-blue-200",
        badge: "bg-blue-300",
        text: "text-white",
        timestampText: "text-blue-100",
    },
    "sunset-sands": {
        author: "AI",
        card: "bg-gradient-to-r from-yellow-400 via-orange-300 to-red-500 shadow-md",
        avatarBorder: "border-2 border-yellow-500 rounded",
        avatarFallback: "bg-yellow-300",
        badge: "bg-yellow-200",
        text: "text-white",
        timestampText: "text-yellow-100",
    },
    "wildflower-meadow": {
        author: "AI",
        card: "bg-gradient-to-r from-lime-400 via-lime-500 to-lime-600 shadow-md",
        avatarBorder: "border-2 border-lime-300 rounded",
        avatarFallback: "bg-lime-200",
        badge: "bg-lime-400",
        text: "text-white",
        timestampText: "text-lime-100",
    },
    "misty-forest": {
        author: "AI",
        card: "bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 shadow-md",
        avatarBorder: "border-2 border-gray-400 rounded",
        avatarFallback: "bg-gray-300",
        badge: "bg-gray-500",
        text: "text-white",
        timestampText: "text-gray-200",
    },
    "canyon-dusk": {
        author: "AI",
        card: "bg-gradient-to-r from-red-600 via-orange-600 to-yellow-700 shadow-md",
        avatarBorder: "border-2 border-red-500 rounded",
        avatarFallback: "bg-red-400",
        badge: "bg-red-500",
        text: "text-white",
        timestampText: "text-red-100",
    },
    "carbon-fiber": {
        author: "AI",
        card: "bg-gradient-to-br from-gray-900 via-gray-800 to-black shadow-lg",
        avatarBorder: "border border-gray-600 rounded",
        avatarFallback: "bg-gray-700",
        badge: "bg-gray-500",
        text: "text-gray-300",
        timestampText: "text-gray-500",
    },
    "arcade-glow": {
        author: "AI",
        card: "bg-black shadow-[0_0_20px_rgba(255,0,255,0.6)] bg-gradient-to-r from-fuchsia-600 via-purple-600 to-indigo-600",
        avatarBorder: "border-2 border-fuchsia-400 rounded",
        avatarFallback: "bg-purple-900",
        badge: "bg-fuchsia-400",
        text: "text-fuchsia-300",
        timestampText: "text-purple-200",
    },
    "deep-space": {
        author: "AI",
        card: "bg-gradient-to-br from-black via-indigo-950 to-black shadow-[0_0_25px_rgba(99,102,241,0.6)]",
        avatarBorder: "border-2 border-indigo-500 rounded",
        avatarFallback: "bg-indigo-900",
        badge: "bg-indigo-500",
        text: "text-indigo-300",
        timestampText: "text-indigo-200",
    },
    "toxic-slime": {
        author: "AI",
        card: "bg-gradient-to-r from-lime-500 via-green-500 to-emerald-600 shadow-[0_0_20px_rgba(132,204,22,0.6)]",
        avatarBorder: "border-2 border-lime-300 rounded",
        avatarFallback: "bg-lime-800",
        badge: "bg-lime-400",
        text: "text-black",
        timestampText: "text-lime-100",
    },
    "ultraviolet": {
        author: "AI",
        card: "bg-gradient-to-r from-violet-700 via-purple-800 to-fuchsia-700 shadow-[0_0_25px_rgba(168,85,247,0.6)]",
        avatarBorder: "border-2 border-violet-400 rounded",
        avatarFallback: "bg-purple-900",
        badge: "bg-violet-400",
        text: "text-violet-200",
        timestampText: "text-purple-200",
    },
    "lava-core": {
        author: "AI",
        card: "bg-gradient-to-r from-red-700 via-orange-700 to-yellow-600 shadow-[0_0_25px_rgba(255,69,0,0.7)]",
        avatarBorder: "border-2 border-orange-500 rounded",
        avatarFallback: "bg-red-900",
        badge: "bg-orange-500",
        text: "text-orange-200",
        timestampText: "text-yellow-200",
    },
    "midnight-teal": {
        author: "AI",
        card: "bg-gradient-to-r from-teal-900 via-teal-800 to-black shadow-lg",
        avatarBorder: "border-2 border-teal-500 rounded",
        avatarFallback: "bg-teal-900",
        badge: "bg-teal-400",
        text: "text-teal-300",
        timestampText: "text-teal-200",
    },
    "glitch-red": {
        author: "AI",
        card: "bg-black shadow-[0_0_25px_rgba(239,68,68,0.7)] bg-gradient-to-r from-red-600 via-black to-red-600",
        avatarBorder: "border-2 border-red-500 rounded",
        avatarFallback: "bg-red-900",
        badge: "bg-red-500",
        text: "text-red-300",
        timestampText: "text-red-200",
    },
    "midnight-synth": {
        author: "AI",
        card: "bg-gradient-to-br from-black via-fuchsia-900 to-cyan-900 shadow-lg shadow-fuchsia-700/40",
        avatarBorder: "border border-fuchsia-500 rounded",
        avatarFallback: "bg-fuchsia-700",
        badge: "bg-cyan-500 text-black",
        text: "text-fuchsia-100",
        timestampText: "text-cyan-300",
    },
};
