name: Deploy

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    release:
        name: Release
        runs-on: ubuntu-24.04-arm
        permissions:
            contents: write
            issues: write
            pull-requests: write
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Setup Node.js
              uses: useblacksmith/setup-node@v5.0.4
              with:
                  node-version: "20"

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10 # Use latest compatible version with your project

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release

    # Get version info - separate job to avoid repeated work
    get_version:
        needs: release

        runs-on: ubuntu-24.04-arm
        outputs:
            version: ${{ steps.package-version.outputs.VERSION }}
            is_prerelease: ${{ steps.prerelease_check.outputs.IS_PRERELEASE }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Read version from package.json
              id: package-version
              run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

            - name: Determine if pre-release
              id: prerelease_check
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  if [[ $VERSION == *"pre"* ]]; then
                    echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
                  else
                    echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
                  fi

    # Build for AMD64 architecture
    build_amd64:
        needs: get_version
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        name: Build Docker image (amd64)
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Login to GitHub Container Registry

              run: echo ${{ secrets.GHCR_LOGIN }} | docker login ghcr.io -u doras-to-admin --password-stdin

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push amd64 Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  platforms: linux/amd64
                  tags: |
                      ghcr.io/dorasto/spotify-overlay:v${{ needs.get_version.outputs.version }}-amd64
                  cache-from: type=gha,scope=amd64
                  cache-to: type=gha,mode=max,scope=amd64

    # Build for ARM64 architecture
    build_arm64:
        needs: get_version
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-24.04-arm
        name: Build Docker image (arm64)
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Login to GitHub Container Registry
              run: echo ${{ secrets.GHCR_LOGIN }} | docker login ghcr.io -u doras-to-admin --password-stdin

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push arm64 Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  platforms: linux/arm64
                  tags: |
                      ghcr.io/dorasto/spotify-overlay:v${{ needs.get_version.outputs.version }}-arm64
                  cache-from: type=gha,scope=arm64
                  cache-to: type=gha,mode=max,scope=arm64

    # Create and publish the multi-arch manifest
    manifest:
        needs: [get_version, build_amd64, build_arm64]
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-24.04-arm
        name: Create and push multi-arch manifest
        steps:
            - name: Login to GitHub Container Registry
              run: echo ${{ secrets.GHCR_LOGIN }} | docker login ghcr.io -u doras-to-admin --password-stdin

            - name: Create manifest list and push
              run: |
                  docker buildx imagetools create -t ghcr.io/dorasto/spotify-overlay:latest -t ghcr.io/dorasto/spotify-overlay:v${{ needs.get_version.outputs.version }} \
                    ghcr.io/dorasto/spotify-overlay:v${{ needs.get_version.outputs.version }}-amd64 \
                    ghcr.io/dorasto/spotify-overlay:v${{ needs.get_version.outputs.version }}-arm64

            - name: Trigger Coolify deployment
              run: |
                  curl --request GET '${{ secrets.COOLIFY_SPOTIFY_OVERLAY_DEPLOY }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_SPOTIFY_OVERLAY }}'
