name: Build Docker Image

on:
    push:
        branches:
            - main
        tags:
            - "v*"

# Required for secrets.GITHUB_TOKEN
permissions:
    packages: write
    contents: read

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: GHCR-Action
              uses: KuhlTime/ghcr-action@v1
              with:
                  token: ${{ secrets.PAT_TOKEN }}
            - name: Trigger Coolify deployment
              run: |
                  curl --request GET '${{ secrets.COOLIFY_SPOTIFY_OVERLAY_DEPLOY }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_SPOTIFY_OVERLAY }}'
